### PR TITLE
Added provider and fixed some overflow errors 

### PR DESCRIPTION
**Pull request by yasaswick**
Added a futureprovider for httprequest,
Added few expanded widgets to fix some overflows

### CODE REVIEW

**Comment by nandunbandara** [comment]
@yasaswick Thank you for contributing. The PR looks fine although I did some change in the following. 
Screen Shot 2020-03-22 at 5 57 00 PM

Could you please center align the values for deaths, recovered and in hospitals?

**Comment by yasaswick** [comment]
Yeah sure ..

**Comment by nandunbandara** [comment]
@yasaswick There are some changes in the master branch for language support by another contributor. Looks like there are some conflicts. Could you please try fixing them as well?

**Comment by yasaswick** [comment]
Btw is there any UI design ? and is a BottomNavigationBar to be implemented ?

**Comment by nandunbandara** [comment]
There was no UI design when I started implementing this. Anyways we might need the bottom navigation bar to resolve issue #2

**Comment by yasaswick** [comment]
I will implement a bottomNav in next commit then , plus is there any idea to implement a map ?

**Comment by yasaswick** [comment]
9df0ddd2-290a-4264-b5e7-6eeb766a685d
6e43d8db-5cda-4c23-9715-594fdac95ee7


Added a bottom nav and two pages for a map and a prevention page , I've commented out the map page because it throws and error on "hot reloading" .. seems like maps api doesn't allow multiple instances l

**Comment by nandunbandara** [comment]
Is this ready for merging @yasaswick I'm reviewing this right now. Thanks for the amazing work.

**Comment by yasaswick** [comment]
@ntbandara3 I just added a pin test pin to the map , and I think the gov. api doesn't supply coordinates of the hospitals , so we might have to use an additional api or just hardcode them atm.

**Comment by nandunbandara** [comment]
@yasaswick the app crashes when I try navigating to the map view. Other than that the rest looks fine. Great work. Yeah the gov api does not supply coordinates. What do you think? Should we just hardcode them for now?

**Comment by nandunbandara** [comment]
@yasaswick I will merge these changes for now and open an issue for the map view crash. Because there are some changes that could conflict with other contributors.

**Comment by yasaswick** [comment]
> @yasaswick the app crashes when I try navigating to the map view. Other than that the rest looks fine. Great work. Yeah the gov api does not supply coordinates. What do you think? Should we just hardcode them for now?

Yeah that's the only simple way I guess ? but I heard they are making new hospitals .. haha , or we can just make a simple json api using firebase realtime database and connect it here .. but it might take a while because you might have to register this app in firebase and get a google service.json for this app.

Btw can you send me the debug output when the app crashes ?

**Pull request merged**
